### ISSUE TITLE
无力吐槽的名字

### ISSUE THREAD

**Issue by truebit** [TencentOpen/GT#9]
quote from built-in dictionary in Mac OS X
> tit |tɪt|
> noun
> ①(songbird)山雀 shānquè
> ②taboo slang (woman's breast)奶子 nǎizi
> ③ British slang (fool)蠢货 chǔnhuò
> ④tit for tat
> (blow for blow)以牙还牙yǐ yá huán yá
> a tit-for-tat response
> 针锋相对的回应zhēn fēng xiāng duì de huíyìng

**Comment by r551** [comment]
悄悄知道就好:)
